### ISSUE TITLE
Consider publishing plugin in official Joplin repo

### ISSUE THREAD

**Issue by graphit0** [xardbaiz/joplin-plugin-hackmd#1]
Link to the repo
https://github.com/joplin/plugins

### Why
This way discovery and updates will be available from inside Joplin

Thanks for your work!

**Comment by xardbaiz** [comment]
Thanks for the idea 🤝 
✅ **Done !** 


For history: Operation completed using [this guide](/laurent22/joplin/tree/dev/packages/generator-joplin#publishing-the-plugin)
