### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by yiugn** [xardbaiz/joplin-plugin-hackmd#4]
Thank you for great hamd plugin, I really appreciate it!
However, I've found a problem, when I share my document by hackmd sharing icon, default note permission for the shared document is set to read: everyone, write:everyone. It should be read: everyone, write : owner only.

Another problem is inability to save version of the document, which is suspected to be related to above problem.

Can you give me some advice?

**Comment by xardbaiz** [comment]
Sorry for the late answer. I was on unexpeted vocation. I will take a look how to solve 1st situation
About versioning - I'm not sure that free plan of HackMD supports it

**Comment by xardbaiz** [comment]
Should be fixed in [v2.0.0](https://github.com/xardbaiz/joplin-plugin-hackmd/releases/tag/2.0.0)
