### ISSUE TITLE
Feature Request: Integrate with the new HackMD API

### ISSUE THREAD

**Issue by Yukaii** [xardbaiz/joplin-plugin-hackmd#5]
Hi @xardbaiz,

I'm Yukai at HackMD. Recently we built the [new API](https://hackmd.io/@hackmd-api/developer-portal) in HackMD, enabling broader possibilities for tools and integrations, for example, [updating or deleting a note](https://hackmd.io/@hackmd-api/developer-portal/https%3A%2F%2Fhackmd.io%2F%40hackmd-api%2Fuser-notes-api). We’ve also released a new [API client](https://github.com/hackmdio/api-client/tree/develop/nodejs) targeting with the new API.

I’ve also found that you raised a PR (https://github.com/hackmdio/api-client/pull/14) for setting the note title. In the new API, you can specify title using markdown h1 syntax, like:

```md
# title
```

We’d like to invite you to enhance the Joplin plugin with the new HackMD API. Feel free to ping us if you encounter any issues or have any great ideas about the new API!

**Comment by xardbaiz** [comment]
Wow! What great news! I will definitely start work on integration using new HMD client soon! 
Thanks a lot!

**Comment by xardbaiz** [comment]
Implemented, merged. PR: #7 
Thanks again for the cool service & API
