### ISSUE TITLE
HackMD  settings do not show up 

### ISSUE THREAD

**Issue by rocky-III** [xardbaiz/joplin-plugin-hackmd#6]
joplin 2.8.8 linux
joplin-hackmd 1.1.0b

HackMD  settings to fill in username & password  do not show up 

on   Open Tools > Options > HackMD
https://global.discourse-cdn.com/standard14/uploads/cozic/original/2X/c/ce36f0d8bde5f09a0c29fa0d3ff793d3ae07f3e9.png

**Comment by alex-rusakevich** [comment]
Same problem

**Comment by navycrow** [comment]
Same problem
Uninstall / reinstall does nothing

**Comment by xardbaiz** [comment]
Thanks guys. I will spend some time to check on the weekend. I guess new version of Joplin just doesn't support old-styled plugins

**Comment by xardbaiz** [comment]
Please check plugin updated version 2.0.0
