### ISSUE TITLE
[Question] Update shared note without changing URL

### ISSUE THREAD

**Issue by schlagmichdoch** [xardbaiz/joplin-plugin-hackmd#8]
Thanks for this great plugin! It works great :)

I have a question regarding the update of an existing note. Your README states:
> Content of already uploaded note could be updated by re-share

The only way I could do this was to:
 1. Remove the added note reference on the bottom of the note
 2. Click the share button again

This way I do have a new public link that points to the shared note but I have two problems:
- The new note is an entirely new note with a different public link so if I shared the public note once I would have to reshare it.
- The old link is still working and points to an outdated version of the note

Is this currently the only way to go or have I missed something?

If so, do you plan to implement real updating via the new API (https://hackmd.io/@hackmd-api/developer-portal/https%3A%2F%2Fhackmd.io%2F%40hackmd-api%2Fuser-notes-api#Update-a-note)

Do you know when hackmd will implement the uploading of images? Their docs only state the following:
> Upload attachments to a note (To be announced)

**Comment by xardbaiz** [comment]
I guess you resolved that issue already with your own PR #10 , right? :)
When note update, link should stay the same (tested manually)

Real update indeed is implemented using the exact API you mentioned. Proof: https://github.com/xardbaiz/joplin-plugin-hackmd/blob/c597cf3364f2620f650947b87cceb6369ff5591c/src/features.ts#L75C1-L77C64

**Comment by schlagmichdoch** [comment]
> When note update, link should stay the same (tested manually)
>
> Real update indeed is implemented using the exact API you mentioned. Proof: https://github.com/xardbaiz/joplin-plugin-hackmd/blob/c597cf3364f2620f650947b87cceb6369ff5591c/src/features.ts#L75C1-L77C64 

Thanks for clarifying! I think that didn’t work though when I tested it the first time. I’ll need to try again in the next days. Maybe something wasn‘t right on my end :)

I had a look at the code which is why I proposed #10 but the issue it fixes isn’t an issue I have had yet.

Btw, for regex development I’m a big fan of https://regex101.com/ which makes testing of expressions and substitutions much easier :)

**Comment by xardbaiz** [comment]
Closed

**Comment by schlagmichdoch** [comment]
Is this fixed though? Is it possible to update a once shared note without resharing it with a new URL?

**Comment by xardbaiz** [comment]
@schlagmichdoch Yes. It should work in [v2.0.0](https://github.com/xardbaiz/joplin-plugin-hackmd/releases/tag/2.0.0)
